export const NUTRIENTS = [
  { code: "SUGAR.added", label: "Added sugar", unit: "g" },
  { code: "CA", label: "Calcium, Ca", unit: "mg" },
  { code: "CHOCDF.net", label: "Carbohydrate (net)", unit: "g" },
  { code: "CHOCDF", label: "Carbohydrate, by difference", unit: "g" },
  { code: "CHOLE", label: "Cholesterol", unit: "mg" },
  { code: "ENERC_KCAL", label: "Energy", unit: "kcal" },
  { code: "FAMS", label: "Fatty acids, total monounsaturated", unit: "g" },
  { code: "FAPU", label: "Fatty acids, total polyunsaturated", unit: "g" },
  { code: "FASAT", label: "Fatty acids, total saturated", unit: "g" },
  { code: "FATRN", label: "Fatty acids, total trans", unit: "g" },
  { code: "FIBTG", label: "Fiber, total dietary", unit: "g" },
  { code: "FOLDFE", label: "Folate, DFE", unit: "µg" },
  { code: "FOLFD", label: "Folate, food", unit: "µg" },
  { code: "FOLAC", label: "Folic acid", unit: "µg" },
  { code: "FE", label: "Iron, Fe", unit: "mg" },
  { code: "MG", label: "Magnesium", unit: "mg" },
  { code: "NIA", label: "Niacin", unit: "mg" },
  { code: "P", label: "Phosphorus, P", unit: "mg" },
  { code: "K", label: "Potassium, K", unit: "mg" },
  { code: "PROCNT", label: "Protein", unit: "g" },
  { code: "RIBF", label: "Riboflavin", unit: "mg" },
  { code: "NA", label: "Sodium, Na", unit: "mg" },
  { code: "Sugar.alcohol", label: "Sugar alcohols", unit: "g" },
  { code: "SUGAR", label: "Sugars, total", unit: "g" },
  { code: "THIA", label: "Thiamin", unit: "mg" },
  { code: "FAT", label: "Total lipid (fat)", unit: "g" },
  { code: "VITA_RAE", label: "Vitamin A, RAE", unit: "µg" },
  { code: "VITB12", label: "Vitamin B-12", unit: "µg" },
  { code: "VITB6A", label: "Vitamin B-6", unit: "mg" },
  { code: "VITC", label: "Vitamin C, total ascorbic acid", unit: "mg" },
  { code: "VITD", label: "Vitamin D (D2 + D3)", unit: "µg" },
  { code: "TOCPHA", label: "Vitamin E (alpha-tocopherol)", unit: "mg" },
  { code: "VITK1", label: "Vitamin K (phylloquinone)", unit: "µg" },
  { code: "WATER", label: "Water", unit: "g" },
  { code: "ZN", label: "Zinc, Zn", unit: "mg" },
];
