export const NUTRIENTS = [
  { code: "SUGAR.added", label: "Added sugar", quantity: 0, unit: "g" },
  { code: "CA", label: "Calcium, Ca", quantity: 0, unit: "mg" },
  { code: "CHOCDF.net", label: "Carbohydrate (net)", quantity: 0, unit: "g" },
  {
    code: "CHOCDF",
    label: "Carbohydrate, by difference",
    quantity: 0,
    unit: "g",
  },
  { code: "CHOLE", label: "Cholesterol", quantity: 0, unit: "mg" },
  { code: "ENERC_KCAL", label: "Energy", quantity: 0, unit: "kcal" },
  {
    code: "FAMS",
    label: "Fatty acids, total monounsaturated",
    quantity: 0,
    unit: "g",
  },
  {
    code: "FAPU",
    label: "Fatty acids, total polyunsaturated",
    quantity: 0,
    unit: "g",
  },
  {
    code: "FASAT",
    label: "Fatty acids, total saturated",
    quantity: 0,
    unit: "g",
  },
  { code: "FATRN", label: "Fatty acids, total trans", quantity: 0, unit: "g" },
  { code: "FIBTG", label: "Fiber, total dietary", quantity: 0, unit: "g" },
  { code: "FOLDFE", label: "Folate, DFE", quantity: 0, unit: "µg" },
  { code: "FOLFD", label: "Folate, food", quantity: 0, unit: "µg" },
  { code: "FOLAC", label: "Folic acid", quantity: 0, unit: "µg" },
  { code: "FE", label: "Iron, Fe", quantity: 0, unit: "mg" },
  { code: "MG", label: "Magnesium", quantity: 0, unit: "mg" },
  { code: "NIA", label: "Niacin", quantity: 0, unit: "mg" },
  { code: "P", label: "Phosphorus, P", quantity: 0, unit: "mg" },
  { code: "K", label: "Potassium, K", quantity: 0, unit: "mg" },
  { code: "PROCNT", label: "Protein", quantity: 0, unit: "g" },
  { code: "RIBF", label: "Riboflavin", quantity: 0, unit: "mg" },
  { code: "NA", label: "Sodium, Na", quantity: 0, unit: "mg" },
  { code: "Sugar.alcohol", label: "Sugar alcohols", quantity: 0, unit: "g" },
  { code: "SUGAR", label: "Sugars, total", quantity: 0, unit: "g" },
  { code: "THIA", label: "Thiamin", quantity: 0, unit: "mg" },
  { code: "FAT", label: "Total lipid (fat)", quantity: 0, unit: "g" },
  { code: "VITA_RAE", label: "Vitamin A, RAE", quantity: 0, unit: "µg" },
  { code: "VITB12", label: "Vitamin B-12", quantity: 0, unit: "µg" },
  { code: "VITB6A", label: "Vitamin B-6", quantity: 0, unit: "mg" },
  {
    code: "VITC",
    label: "Vitamin C, total ascorbic acid",
    quantity: 0,
    unit: "mg",
  },
  { code: "VITD", label: "Vitamin D (D2 + D3)", quantity: 0, unit: "µg" },
  {
    code: "TOCPHA",
    label: "Vitamin E (alpha-tocopherol)",
    quantity: 0,
    unit: "mg",
  },
  {
    code: "VITK1",
    label: "Vitamin K (phylloquinone)",
    quantity: 0,
    unit: "µg",
  },
  { code: "WATER", label: "Water", quantity: 0, unit: "g" },
  { code: "ZN", label: "Zinc, Zn", quantity: 0, unit: "mg" },
];
